name: LightWidget
options:
  bundleIdPrefix: com.ollygadiot
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"

targets:
  LightWidget:
    type: application
    platform: macOS
    sources:
      - LightWidget
    info:
      path: LightWidget/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: LightWidget
        CFBundleName: LightWidget
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    entitlements:
      path: LightWidget/LightWidget.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ollygadiot.LightWidget
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: LightWidget
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_FILE: LightWidget/Info.plist
        INFOPLIST_KEY_LSUIElement: true
